### ISSUE TITLE
'Module' object has no attribute 'BoneGroups' error

### ISSUE THREAD

**Issue by ki-ki-key** [MMD-Blender/blender_mmd_tools_append#147]
<img width="1042" height="471" alt="Image" src="https://github.com/user-attachments/assets/ced93849-fc4c-427e-8bb5-6dc704099435" />

I tried to install the add on but it gives me this error. Is there any fix to this? I have MMD tools installed correctly.

**Comment by RustyNova016** [comment]
The add-on only works on 3.6.x. Not 4.2.
Import your model and modify it in 3.6, then import in 4.2

**Comment by ulyssas** [comment]
This is the table of matching versions of Blender, MMD Tools and MMD Tools Append (formerly UuuNyaa Tools)
| Blender LTS Version | MMD Tools Version | MMD UuuNyaa Tools Version |
| ------------------- | ----------------- | ------------------------- |
| Blender 4.2 & 4.5   | MMD Tools v4.x    | MMD Tools Append v4.x     |
| Blender 3.6         | MMD Tools v2.10.3 | UuuNyaa Tools v1.8.0      |
| Blender 2.93        | MMD Tools v2.10.3 | UuuNyaa Tools v1.7.2      |
| Blender 2.83        | MMD Tools v2.5.1  | UuuNyaa Tools v1.6.0      |

**Comment by ulyssas** [comment]
## For Blender 4.2+ users
The latest release of [MMD Tools Append v4.5.3](https://github.com/MMD-Blender/blender_mmd_tools_append/releases/tag/v4.5.3) now works properly on Blender 4.2 and later. You need to install ZIP file from Blender Preferences. Make sure you have installed MMD Tools first.

## For Blender 4.0 & 4.1 users
Install [MMD Tools Addon](https://github.com/ulyssas/mmd_tools_addon_4.2/releases/tag/v4.5.1_addon) and [patched UuuNyaa Tools](https://github.com/ulyssas/mmd_uuunyaa_tools_4.2/releases/tag/v1.8.0_patch). Some features are missing in this patched UuuNyaa Tools. If you need them, you can create issues in the repository.
